version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Shanghai
    command: --default-time-zone='+08:00'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    depends_on:
      - app
    networks:
      - frontend
      - backend

volumes:
  db_data:

networks:
  frontend:
  backend:
