version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    # ports:
      # - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    # ports:
      # - "3306:3306"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
      # - ./certs/localhost.crt:/etc/ssl/certs/localhost.crt
      # - ./certs/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - app